from typing import Any, Dict, List
from app.models.schemas import ChatResponse
from app.utils.logger import logger

class ResponseValidator:
    """Validates generated agent responses against schema bounds and catalog constraints."""

    def validate(self, response: ChatResponse, catalog: List[Dict[str, Any]]) -> bool:
        """Validates recommended items.

        Args:
            response: ChatResponse generated by the agent.
            catalog: Scraped SHL catalog list.

        Returns:
            True if valid, False if violations are detected.
        """
        logger.info("Validating generated recommendations against catalog constraints...")

        # Turn level recommendation bounds check (1 to 10)
        recs = response.recommendations
        if recs and (len(recs) < 1 or len(recs) > 10):
            logger.error(f"Validation Error: recommendation list length {len(recs)} out of bounds (1-10 limit)")
            return False

        # Build indices for faster lookup validation
        valid_names = {item.get("name", "").strip().lower() for item in catalog}
        valid_urls = {item.get("link", "").strip().lower() for item in catalog}

        # Check grounding for each recommended assessment
        for item in recs:
            name_norm = item.name.strip().lower()
            url_norm = item.url.strip().lower()

            if name_norm not in valid_names:
                logger.error(f"Validation Error: Assessment '{item.name}' is not in the SHL catalog.")
                return False

            if url_norm not in valid_urls:
                logger.error(f"Validation Error: Assessment URL '{item.url}' does not match the SHL catalog.")
                return False

            if not item.test_type:
                logger.error(f"Validation Error: Assessment '{item.name}' is missing test_type classification.")
                return False

        logger.info("Response successfully validated against catalog rules.")
        return True
